### ISSUE TITLE
Collection Schema doesn't exist

### ISSUE THREAD

**Issue by abrin** [openschemas/schemaorg#34]
**Describe the bug**

Hi, I was able to find the definitions for a collection schema in the [csv] (https://raw.githubusercontent.com/openschemas/schemaorg/master/schemaorg/data/releases/7.03/all-layers-types.csv), and JSON-LD files, but when you try and use it, it's reported that it doesn't exist (here's the output of the test I created (below). Not sure I'm missing something though?:

```
Specification base set to http://www.schema.org
Using Version 7.03
Collection
Did you mean:
CollectionPage
---------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------
WARNING /Users/abrin/schemaorg/recipe.yml does not exist.
WARNING /Users/abrin/schemaorg/recipe.yml does not exist.
ERROR Collection is not a valid type!
```

**To Reproduce**

I created a basic test:

```
from schemaorg.templates.google import make_person
from schemaorg.main.parse import RecipeParser
from schemaorg.main import Schema
import shutil
import os
import unittest
import tempfile

print("######################################################## test_schema")

class TestSchema(unittest.TestCase):

    def setUp(self):
        self.tmpdir = os.path.join(tempfile.gettempdir(), 'schemaorg-test')

        if not os.path.exists(self.tmpdir):
            os.mkdir(self.tmpdir)


    def tearDown(self):
        pass


    def test_collection(self):

        self.here = os.path.abspath(os.path.dirname(__file__))
        recipe_yml = os.path.join(self.here, "recipe.yml")
        self.recipe = RecipeParser(recipe_yml)
        self.collection = Schema("Collection")
        self.collection.add_property('name', 'test')
        self.collection.validate(self.collection)



if __name__ == '__main__':
    unittest.main()
```

### recipe.yml
```
version: 1
schemas:
  Dataset:
    recommended:
      - softwareVersion: version
      - citation
      - identifier
      - keywords
      - license
      - url
      - sameAs
      - spatialCoverage
      - temporalCoverage
      - variableMeasured
      - includedInDataCatalog
    required:
      - description
      - name
  Person|Organization:
    required:
      - description
      - name
  Collection:
    required:
      - name


```

thanks 
**Version of Python schemaorg**
latest
